version: '3.3'
services:
  cassandra:
    image: cassandra-no-local-jmx:3.11.3
    ports:
      - 9042:9042
      - 7199:7199
    environment:
      - LOCAL_JMX=no
      - JVM_EXTRA_OPTS=-Djava.rmi.server.hostname=127.0.0.1
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    container_name: cassandra
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra-no-local-jmx:3.11.3
    depends_on:
      - cassandra
    volumes:
      - ./initdb/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
